import { Github, Linkedin, Mail, Twitter } from "lucide-react";

export const DATA = {
    name: "MD Mukit Hasan",
    profilePicture: "/me.png",
    role: "Full Stack Developer & AI Specialist",
    headline: "MD MUKIT HASAN: Engineering the Future with Code & AI.",
    subheading: "Founder @ CoderNest Digital Solutions | Full Stack Web Developer specializing in Next.js, Node.js, and AI Orchestration.",
    cta: {
        primary: "View My Work",
        secondary: "Let's Collaborate",
    },
    socials: [
        {
            name: "GitHub",
            url: "https://github.com/mukithasan232",
            icon: Github,
        },
        {
            name: "LinkedIn",
            url: "https://www.linkedin.com/in/md-mukit-hasan-bd",
            icon: Linkedin,
        },
        {
            name: "Twitter",
            url: "https://twitter.com/mukithasan232",
            icon: Twitter,
        },
        {
            name: "Business Email",
            url: "mailto:codernestwebsolution@gmail.com",
            icon: Mail,
        },
    ],
    contact: {
        email: "codernestwebsolution@gmail.com",
        personalEmail: "mdmukithasan689@gmail.com",
    },
    stats: [
        { label: "Projects Delivered", value: "10+" },
        { label: "Technologies Mastered", value: "12+" },
        { label: "Client Satisfaction", value: "100%" },
        { label: "Years Building", value: "2+" },
    ],
    about: {
        title: "About Me",
        description: "I'm MD Mukit Hasan — a Full Stack Web Developer and AI Specialist based in Bangladesh, currently studying Information and Communication Engineering (ICE) at Daffodil International University. I'm the founder of CoderNest Digital Solutions, where I build high-performance SaaS products, AI-powered tools, and scalable web applications.\n\nMy passion lies at the intersection of great engineering and cutting-edge AI. I specialize in architecting full-stack solutions with Next.js, Node.js, PostgreSQL, and Prisma — integrating AI capabilities through the Gemini API and other LLM orchestration tools to build products that genuinely solve real-world problems.\n\nEvery line of code I write is driven by the belief that technology should create measurable impact. I'm always looking for the next challenge that pushes the boundaries of what's possible.",
    },
    techStack: [
        { name: "Next.js", icon: "▲", color: "#ffffff" },
        { name: "React", icon: "⚛", color: "#61dafb" },
        { name: "Node.js", icon: "⬡", color: "#68a063" },
        { name: "TypeScript", icon: "TS", color: "#3178c6" },
        { name: "Tailwind CSS", icon: "◈", color: "#38bdf8" },
        { name: "PostgreSQL", icon: "🐘", color: "#336791" },
        { name: "Prisma", icon: "◆", color: "#5a67d8" },
        { name: "Gemini API", icon: "✦", color: "#4285f4" },
        { name: "Firebase", icon: "🔥", color: "#f59e0b" },
        { name: "Git", icon: "⎇", color: "#f05032" },
        { name: "Docker", icon: "🐳", color: "#2496ed" },
        { name: "REST APIs", icon: "⟷", color: "#10b981" },
    ],
    skills: {
        frontend: [
            { name: "Next.js / React", level: 90 },
            { name: "TypeScript", level: 82 },
            { name: "Tailwind CSS", level: 92 },
            { name: "HTML5 / CSS3", level: 95 },
        ],
        backend: [
            { name: "Node.js / Express", level: 80 },
            { name: "PostgreSQL / Prisma", level: 78 },
            { name: "REST API Design", level: 85 },
            { name: "Gemini API / AI Integration", level: 75 },
        ],
    },
    projects: [
        {
            title: "MedOS",
            tagline: "Hospital Management SaaS",
            problem: "Healthcare facilities struggle with fragmented, outdated systems that make scheduling, patient tracking, and billing inefficient.",
            solution: "Built a modern full-stack SaaS platform with role-based auth, real-time analytics dashboard, and seamless patient management.",
            tech: ["Next.js", "Prisma ORM", "PostgreSQL", "NextAuth.js", "Tailwind CSS"],
            result: "Highly secure, responsive portal that optimizes daily hospital workflows and provides clear financial analytics.",
            live: "https://hospital-management-portal-nu.vercel.app/",
            github: "https://mukithasan232.github.io/hospital_management_portal/",
            aiPowered: false,
            featured: true,
            images: [
                "/project5-screenshot1.png",
                "/project5-screenshot2.png",
                "/project5-screenshot3.png",
                "/project5-screenshot4.png",
                "/project5-screenshot5.png",
                "/project5-screenshot6.png",
                "/project5-screenshot7.png",
                "/project5-screenshot8.png",
            ],
        },
        {
            title: "MediStore Lite",
            tagline: "AI-Powered Pharmacy POS & Inventory",
            problem: "Pharmacy POS systems are outdated, slow, and lack intelligent inventory management capabilities.",
            solution: "Developed an AI-powered pharmacy POS with smart inventory tracking, expiry alerts, and automated reorder suggestions powered by AI.",
            tech: ["Next.js", "Node.js", "Gemini API", "PostgreSQL", "Prisma"],
            result: "Streamlined pharmacy operations with 60% reduction in manual inventory tasks and zero stockout incidents.",
            live: "https://hospital-management-portal-nu.vercel.app/",
            github: "#",
            aiPowered: true,
            featured: true,
            images: [
                "/project5-screenshot9.png",
                "/project5-screenshot10.png",
                "/project5-screenshot11.png",
                "/project5-screenshot12.png",
            ],
        },
        {
            title: "SMM Elite",
            tagline: "Automated SMM Reseller Panel",
            problem: "Managing and reselling thousands of social media services manually is inefficient, with no seamless payment or API bridging.",
            solution: "Built a premium fully-automated SMM Reseller Panel integrating SMMGen API with instant order routing and localized payment processing.",
            tech: ["Next.js", "RESTful APIs", "MySQL", "JavaScript", "bKash / Nagad"],
            result: "Scalable platform bridging users to 6,000+ digital services with automated profit margins and async data handling.",
            live: "https://smm-panel-liart.vercel.app/",
            github: "https://mukithasan232.github.io/smm_panel/",
            aiPowered: false,
            featured: true,
            images: [
                "/project6-screenshot1.png",
                "/project6-screenshot2.png",
                "/project6-screenshot3.png",
                "/project6-screenshot4.png",
                "/project6-screenshot5.png",
            ],
        },
        {
            title: "AI Web Builder",
            tagline: "AI-Powered Website Generator",
            problem: "Manually building websites is time-consuming and requires technical expertise.",
            solution: "Developed an AI-powered web builder that generates fully functional websites with customizable themes, AI chatbots, and automated SEO.",
            tech: ["Next.js", "React", "Tailwind CSS", "Node.js", "OpenAI API"],
            result: "Users can launch modern, responsive websites in minutes without coding.",
            live: "https://ai-powerd-website-builder.netlify.app/",
            github: "https://github.com/mukithasan232/ai-powerd-website-builder",
            aiPowered: true,
            featured: false,
            images: [
                "/project3-screenshot1.png",
                "/project3-screenshot2.png",
                "/project3-screenshot3.png",
            ],
        },
        {
            title: "AffiliatePro",
            tagline: "Amazon Affiliate Platform",
            problem: "Amazon affiliate marketers struggle with slow, unoptimized websites and lack of real-time product data syncing.",
            solution: "Built a premium Affiliate Marketing platform with SSR for SEO, automated product discovery, and a robust admin dashboard.",
            tech: ["Next.js", "Tailwind CSS", "PostgreSQL", "Redis", "Neon DB"],
            result: "Scalable, SEO-friendly platform allowing founders to launch affiliate sites quickly with minimal maintenance.",
            live: "https://simple-affilliate-site.vercel.app/",
            github: "https://mukithasan232.github.io/simple-affilliate-site/",
            aiPowered: false,
            featured: false,
            images: [
                "/project4-screenshot1.png",
                "/project4-screenshot2.png",
                "/project4-screenshot3.png",
            ],
        },
        {
            title: "Digital Orchard",
            tagline: "Premium Mango Marketplace",
            problem: "Local farmers in Bangladesh struggle to reach consumers, relying on middlemen with unfair pricing.",
            solution: "Full-stack e-commerce marketplace with comprehensive admin dashboard, secure role-based login, and seamless storefront.",
            tech: ["Next.js", "Tailwind CSS", "React", "PostgreSQL", "Vercel Analytics"],
            result: "SEO-ready platform connecting farmers to nationwide audience with real-time order tracking.",
            live: "https://digital-orchard.vercel.app/",
            github: "https://mukithasan232.github.io/digital_orchard/",
            aiPowered: false,
            featured: false,
            images: [
                "/project7-screenshot1.png",
                "/project7-screenshot2.png",
                "/project7-screenshot3.png",
            ],
        },
    ],
    services: [
        {
            title: "MVP Development",
            description: "From idea to live product in weeks. I architect and build full-stack MVPs that are production-ready, scalable, and investor-ready.",
            icon: "🚀",
            features: ["Rapid prototyping", "Full-stack architecture", "CI/CD deployment"],
        },
        {
            title: "AI Integration",
            description: "Embed cutting-edge AI capabilities into your products — chatbots, recommendation engines, automation, and LLM orchestration with Gemini API.",
            icon: "🤖",
            features: ["LLM orchestration", "Gemini / OpenAI APIs", "AI automation"],
        },
        {
            title: "Full Stack Web Apps",
            description: "End-to-end web applications built with Next.js, Node.js, and PostgreSQL. Optimized for performance, SEO, and exceptional user experience.",
            icon: "⚡",
            features: ["Next.js + Node.js", "PostgreSQL + Prisma", "REST API design"],
        },
        {
            title: "SaaS Consulting",
            description: "Strategic technical guidance for SaaS founders — from architecture planning and database design to scaling strategies and API integrations.",
            icon: "💡",
            features: ["Architecture planning", "Database design", "Scaling strategy"],
        },
    ],
    experience: [
        {
            year: "2025 - Present",
            role: "Founder & Full Stack Developer",
            company: "CoderNest Digital Solutions",
            description: "Founded and operate a digital solutions agency building SaaS products, AI-powered tools, and scalable web applications for global clients.",
        },
        {
            year: "2024 - Present",
            role: "ICE Student",
            company: "Daffodil International University",
            description: "Studying Information and Communication Engineering, merging academic knowledge with hands-on full stack development and AI integration projects.",
        },
        {
            year: "2024",
            role: "Freelance Web Developer",
            company: "Upwork / Direct Clients",
            description: "Built custom web solutions for clients across e-commerce, healthcare, and social media sectors using React, Next.js, and Firebase.",
        },
    ],
    testimonials: [
        {
            name: "Startup Founder",
            role: "SaaS Client",
            content: "Mukit built our entire MVP in just 3 weeks. The code quality and the AI features he integrated were beyond what we expected. Highly recommend!",
            avatar: "SF",
        },
        {
            name: "Healthcare Director",
            role: "MedOS Client",
            content: "MedOS transformed how our hospital manages patient data. The real-time analytics alone saved us hours every day. Outstanding work.",
            avatar: "HD",
        },
    ],
    blog: [
        {
            title: "Building AI-Powered SaaS with Next.js & Gemini API",
            excerpt: "How I orchestrated LLM capabilities into production apps without breaking the bank.",
            date: "Apr 15, 2026",
            category: "AI",
            image: "/blog-react-tailwind.png"
        },
        {
            title: "From Idea to MVP in 3 Weeks: My Workflow",
            excerpt: "The exact process I use to ship full-stack MVPs rapidly — architecture, tools, and deployment.",
            date: "Mar 20, 2026",
            category: "Development",
            image: "/blog-firebase.png"
        },
        {
            title: "Why PostgreSQL + Prisma is My Go-To Stack",
            excerpt: "Type-safe database queries, migrations, and relational power — why I switched from Firebase.",
            date: "Feb 10, 2026",
            category: "Backend",
            image: "/blog-career-mistakes.png"
        },
        {
            title: "SEO-First Architecture in Next.js 14",
            excerpt: "Server components, metadata API, and structured data — how to rank on Google with Next.js.",
            date: "Jan 28, 2026",
            category: "SEO",
            image: "/blog-seo.png"
        },
    ],
    mapUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3596.73352!2d88.7767625!3d25.6473352!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39fb55eb718e02d9%3A0x32fd0be634d9111c!2sCoderNest!5e0!3m2!1sen!2sbd!4v1710000000000!5m2!1sen!2sbd",
};
